/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CheatsRouteImport } from './routes/cheats'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheatsIdRouteImport } from './routes/cheats.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatsRoute = CheatsRouteImport.update({
  id: '/cheats',
  path: '/cheats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatsIdRoute = CheatsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CheatsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cheats': typeof CheatsRouteWithChildren
  '/community': typeof CommunityRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/cheats/$id': typeof CheatsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cheats': typeof CheatsRouteWithChildren
  '/community': typeof CommunityRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/cheats/$id': typeof CheatsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cheats': typeof CheatsRouteWithChildren
  '/community': typeof CommunityRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/cheats/$id': typeof CheatsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cheats'
    | '/community'
    | '/features'
    | '/login'
    | '/cheats/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cheats'
    | '/community'
    | '/features'
    | '/login'
    | '/cheats/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cheats'
    | '/community'
    | '/features'
    | '/login'
    | '/cheats/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheatsRoute: typeof CheatsRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheats': {
      id: '/cheats'
      path: '/cheats'
      fullPath: '/cheats'
      preLoaderRoute: typeof CheatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheats/$id': {
      id: '/cheats/$id'
      path: '/$id'
      fullPath: '/cheats/$id'
      preLoaderRoute: typeof CheatsIdRouteImport
      parentRoute: typeof CheatsRoute
    }
  }
}

interface CheatsRouteChildren {
  CheatsIdRoute: typeof CheatsIdRoute
}

const CheatsRouteChildren: CheatsRouteChildren = {
  CheatsIdRoute: CheatsIdRoute,
}

const CheatsRouteWithChildren =
  CheatsRoute._addFileChildren(CheatsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheatsRoute: CheatsRouteWithChildren,
  CommunityRoute: CommunityRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
